language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # MATTERMOST_HOOK_URL
  - secure: liaC15r7mn5DHsvZlfF6ikq0T29HfRbCcx5GaNnzebhoW2Z04rs3H5pWHOKpd2k0mSpENc8R0H9wAJ4DUp0CF+e9Sm6JCx1OEHqFgp2Xj4O5ZAx2QHLpKgQDnsNoGRvoOAMguzioU29fBwgG+C9dQ6BeZ+gKUYboH/4xc7B0bxM2W0aKctPnJIZTIPdGlJ765xlS0VJsVm8QFLn7u84AWBWFLQefBcyTEtEezX2nr/EAY6XO3zDTy2w9pezaAwHIoxcHghB1ioeIaRaOcx+34CqrC0vQkCqnIqEnui9oI3/qg/+M4/BpF/VIFzS0CbucQyYsPvi39F17VJvLhuVj386mBEMCI5kW89P+EuOQGx3HoBbPAjCmhfp7JtsGLIV5x11h3Gc+T3DFrqbKSCdGIEoO64XcIfhPRfIQ2bMmrMNE83F6U1+1rsU2BrQN6eF64sc0tepuyks3Px6o3zKryq2u7PLRNWh5ROGhlwDX8ZbISUlLKsrVexWG4sViNs3MD5FvGGhL/qf8Cw0RcMjcFk03GeA5uxoI7GumyQxq6n4p19xlLyMaM5p5GIxF3GEOoWqNSxuPkG3XElMmljKE76Z0FIWx12g5F9NY9y8YaBZ7vo5SSMLIlMb7+KsGZjL4g8t5NNcj3yNEAICyK+BNOxPPKKFj+9eHtEjHjrjOzUw=
  # REGISTRY_TOKEN slug=cdiscount editor=cozy space=cozy_ccc
  - secure: moAkSd1rEdVMXuIqlSYHR9GY5xC5KwOOFOnVT1F8lW1/hR8JsPPKoPojZqXz6jgtMJgNETZ0NcxdckgrJqAkBB7omf5VTZj3AYR2i7OjObZ2j+Atl9ejn1VmyTMbZhNsjfzjWmZ5aQXc5eKGHwdEDhpNV58UK3pyRz5M4vR90hFRhXBstpCdb72wKFIrxDA12+EhY/AU/y4A/o8DeTSE2qn0JBxKCRqwJGfIbeHPMcUmbkRT4v3nTOMY/qhNrlwGJfYDRBihT9kABUbVGO+I37c91AstLEW/Uinq4mnKAGab6X8DgEtI0FRvMMs4uI/zPNZJpo9I3eX8tHe+odPYN5l1ACcE8UEKcAGz5sFbBoRIShMQglLvefg+UAcGkkUKVQuqCxS7e5JDJEV8b+zU4L+oLaHYjAeq1ZAf1cBbPFSddi2v3BR/9tl9DPethlSjtcMLZ6OcNsqa8icWBlwq0AEjks4tWPgc5faUjIatr8BMwDH+tIJN/OV85ozaOugpPgc91/xmFd90UFH2d+h9dQMy/jBURlX1uUCAj5HESXmJeTrTtYQXli/IRcyZAhjFsXQ6MM2NMPZwtuWRbH5QnlqeQM9QWbPh86BsigDtoy3Kna86+Bv5GgSyrsyizZk6PVyguBBvv1ii2BLtGC4J0/s/abfWlAml557KFRsyrVk=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --space cozy_ccc
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost --space cozy_ccc
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
