language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # MATTERMOST_HOOK_URL
  - secure: liaC15r7mn5DHsvZlfF6ikq0T29HfRbCcx5GaNnzebhoW2Z04rs3H5pWHOKpd2k0mSpENc8R0H9wAJ4DUp0CF+e9Sm6JCx1OEHqFgp2Xj4O5ZAx2QHLpKgQDnsNoGRvoOAMguzioU29fBwgG+C9dQ6BeZ+gKUYboH/4xc7B0bxM2W0aKctPnJIZTIPdGlJ765xlS0VJsVm8QFLn7u84AWBWFLQefBcyTEtEezX2nr/EAY6XO3zDTy2w9pezaAwHIoxcHghB1ioeIaRaOcx+34CqrC0vQkCqnIqEnui9oI3/qg/+M4/BpF/VIFzS0CbucQyYsPvi39F17VJvLhuVj386mBEMCI5kW89P+EuOQGx3HoBbPAjCmhfp7JtsGLIV5x11h3Gc+T3DFrqbKSCdGIEoO64XcIfhPRfIQ2bMmrMNE83F6U1+1rsU2BrQN6eF64sc0tepuyks3Px6o3zKryq2u7PLRNWh5ROGhlwDX8ZbISUlLKsrVexWG4sViNs3MD5FvGGhL/qf8Cw0RcMjcFk03GeA5uxoI7GumyQxq6n4p19xlLyMaM5p5GIxF3GEOoWqNSxuPkG3XElMmljKE76Z0FIWx12g5F9NY9y8YaBZ7vo5SSMLIlMb7+KsGZjL4g8t5NNcj3yNEAICyK+BNOxPPKKFj+9eHtEjHjrjOzUw=
  # REGISTRY_TOKEN(editor=cozy, app=cdiscount)
  - secure: N33rzLi51ldrIxtQBs93D0+RaGAJB1T49WdwQcrigTTHJgXvP+1TUDn45N/wJbxE1fdqd8Cn8xU/8oJZMXDjPCU00wY/u/EYDJdU3DnZ01CR3bWT1EuGmOw92OX/+01AUwwv8slOp/kW14nbTNkKBbBFvie/fxrrbrhdtY7kM8xodfnYHNv9W6uR5ntyhF1o7Jey3o3qByRg82vdWtW7kIQUkPGK1OYcA1fIFeB5tSxonGNg9Xs8UC53vcBW7BP1EPbY8jAb5HVZpd/HsaLYxRqaglGRMhAjMZAyOgkT5TsCERvjbswZcS8Yil2SpdauVGPCo5OKd9pdjrlE+j3+9UCNO/tXQKxuC/5hSW2CDFxc+QP2TjTsDDZouAi/GipfhFXNt/QJUZ//EDElzXB2ugLi4Bpuq8zHp6wXKbl25XqEivCtglFdTSXdmfOau1Zo9781rbZv+VOkhiWT9ReTSWSEju3forBeENjACFez/E62Ky0aHK27kCBiM7FbZ0Zp1BNY99NGfJNeBac3i5S6HIvv18tV6EweZ1hVgYZJ9SVs+HiE5lXJ8mJn1+2mCkOWtM6FukOGHOVNIWd0eQvEEiG7UmEbmkJPy6UWrPMFEqejRGHnivzqtPjLo+w1VryOaiCWYOX5Z7u+RyCy6e+ThjiTaYeJVkHwcJnXTvbgB/A=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
